# -*- coding: utf-8 -*-
"""ForageAccenture.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YgeX4qEvwf0WlnUVDAxVNMvoMWMvHUbB

# Importing Modules
"""

import pandas as pd
import numpy as np
import matplotlib as plt

# https://drive.google.com/file/d/18Vy24f7Hknv0pqm4a0u0jr_VYgZSlB6x/view?usp=sharing
# https://drive.google.com/file/d/1qVQ34AXPMk0dxqbu8HbKbubu8LWHKdyk/view?usp=sharing
# https://drive.google.com/file/d/1DlvSLg6Al5T-roY1UfVgsvgiknPkoIsa/view?usp=sharing

"""# Getting the Data"""

!gdown 18Vy24f7Hknv0pqm4a0u0jr_VYgZSlB6x
!gdown 1qVQ34AXPMk0dxqbu8HbKbubu8LWHKdyk
!gdown 1DlvSLg6Al5T-roY1UfVgsvgiknPkoIsa

content = pd.read_csv('/content/Content.csv')
reactions = pd.read_csv('/content/Reactions.csv')
reactiontypes = pd.read_csv('/content/ReactionTypes.csv')

"""# Content"""

content.head()

content.shape

content.isnull().sum()

content.columns

# dropping 'Unnamed: 0', 'User ID', 'URL'
content = content[['Content ID', 'Type', 'Category']]

content.shape

content.isnull().sum()

content.columns

# Rename columns
content.rename(columns={'Type': 'Content_Type'}, inplace=True)

content['Category'] = content['Category'].str.strip('"').str.lower()

content['Category'].value_counts()

"""# Reactions"""

reactions.head()

reactions.shape

reactions.isnull().sum()

# dropping columns that are not needed
reactions = reactions[['Content ID', 'Type']]

reactions = reactions.dropna()

# Rename columns
reactions.rename(columns={'Type': 'Reaction_Type'}, inplace=True)

reactions.columns

reactions['Reaction_Type'] = reactions['Reaction_Type'].str.replace('"', '')

"""# Reaction Types"""

reactiontypes.head(16)

reactiontypes.shape

reactiontypes.isnull().sum()

reactiontypes= reactiontypes[['Type', 'Score']]

# Rename columns
reactiontypes.rename(columns={'Type': 'Reaction_Type'}, inplace=True)

"""# Join Datasets"""

merged_df1 = pd.merge(reactions,content, on=['Content ID'], how='inner')

merged_df1

merged_df2 = pd.merge(merged_df1,reactiontypes, on=['Reaction_Type'], how='inner')

merged_df2

sorted_df = merged_df2.sort_values(by='Score', ascending=False)

sorted_df

"""## Grouby and Sum"""

sorted_df2 = sorted_df.groupby('Category').agg({'Score': 'sum'})
sorted_df2

sorted_df2 = sorted_df2.sort_values(by='Score', ascending=False)

sorted_df2

# Values you want to select
selected_values = ['animals', 'healthy eating', 'technology','science', 'food']

# Use boolean indexing to select rows with the specified values in 'Category'
selected_rows = sorted_df[sorted_df['Category'].isin(selected_values)]

# Display the selected rows
selected_rows

selected_rows = selected_rows.reset_index()

selected_rows = pd.DataFrame(selected_rows)
selected_rows

selected_rows.columns

# Final DataFrame
Top5Cat = selected_rows[['Content ID', 'Reaction_Type', 'Content_Type', 'Category', 'Score']]

Top5Cat

from google.colab import files

# To download the DataFrame in CSV Format


# selected_rows.to_csv('Top5Cat.csv', index=False)

# # Download the CSV file
# files.download('Top5Cat.csv')

"""# Visualizations for insights

## Downloading Final DataFrame from Above
"""

# The final dataframe after downloading it in CSV format

# https://drive.google.com/file/d/14cMw8Gofh5OJzs10PAfWGdMmtpenTCHM/view?usp=sharing
!gdown 14cMw8Gofh5OJzs10PAfWGdMmtpenTCHM

final = pd.read_csv('/content/Task 3_Final Content Data set.csv')

temp = final.groupby('Category').agg({'Score':'sum'}).sort_values(by = 'Score', ascending = False)
temp

# Values you want to select
selected_values = ['animals', 'healthy eating', 'technology','science', 'food']

# Use boolean indexing to select rows with the specified values in 'Category'
final = final[final['Category'].isin(selected_values)]

# Display the selected rows
final

"""## Visualization 1"""

final['Category'].value_counts()

new = final.groupby('Category').agg({'Score':'sum'})

new = pd.DataFrame(new)
new = new.reset_index()

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 8))
plt.pie(new['Score'], labels=new['Category'], autopct='%1.1f%%', startangle=90, colors=['#ff9999', '#66b3ff', '#90ff99', '#ffcc99', '#c2c2f0'])
plt.title('Distribution of Categories')
plt.show()

"""## Visualization 2"""

reactions2 = pd.read_csv('/content/Reactions.csv')

reactions2.dropna()

reactions2.isnull().sum()

reactions2 = reactions2[['Content ID', 'Datetime']]

import pandas as pd

# Assuming 'Datetime' is in string format
reactions2['Datetime'] = pd.to_datetime(reactions2['Datetime'])

# Now you can apply the strftime method
reactions2['Formatted_Date'] = reactions2['Datetime'].apply(lambda x: x.strftime("%m"))

new4 = reactions2.groupby('Formatted_Date').agg({"Content ID":'count'})

import matplotlib.pyplot as plt

# Assuming new4 is a DataFrame
new4.plot(kind='line', figsize=(15, 5), color=['blue', 'green', 'red'], legend = False)

# Adding labels and title
plt.xlabel('Month')
plt.ylabel('Count of Content')
plt.title('Line Plot  by Months')

# Display the plot
plt.show()